shadowMapResolution=2048
option.REMOVE_GRASS=false 
shadowDistance=128.0
colortex2=RGBA16F
uniform.float.isJungle=smooth(1, if(in(biome, BIOME_JUNGLE, BIOME_SPARSE_JUNGLE, BIOME_BAMBOO_JUNGLE), 1, 0), 25, 25)
uniform.float.isSavanna=smooth(2, if(in(biome, BIOME_SAVANNA, BIOME_SAVANNA_PLATEAU, BIOME_WINDSWEPT_SAVANNA), 1, 0), 25, 25)
uniform.float.isDesert=smooth(3, if(in(biome, BIOME_DESERT, BIOME_BADLANDS, BIOME_ERODED_BADLANDS, BIOME_WOODED_BADLANDS), 1, 0), 25, 25)
uniform.float.isSwamp=smooth(4, if(in(biome, BIOME_SWAMP, BIOME_MANGROVE_SWAMP), 1, 0), 25, 25)
uniform.float.isCold=smooth(5, if(in(biome, BIOME_SNOWY_PLAINS, BIOME_ICE_SPIKES, BIOME_SNOWY_TAIGA, BIOME_FROZEN_RIVER, BIOME_FROZEN_OCEAN, BIOME_FROZEN_PEAKS, BIOME_JAGGED_PEAKS, BIOME_SNOWY_SLOPES, BIOME_GROVE), 1, 0), 25, 25)